## NumPy : Practice Problems 1
Easy Questions : 7
Moderate Questions : 7
Hard Questions : 3
<hr>


### 1. Write a NumPy program to get the numpy version and show numpy build configuration.

Level: Easy

In [1]:
import numpy as np

print(np.version.version)
print(np.__config__)

1.18.1
<module 'numpy.__config__' from '/Users/Shreyu/opt/anaconda3/lib/python3.7/site-packages/numpy/__config__.py'>


### 2. Create a null vector of size 10 but the fifth value which is 1.

Level: Easy

In [3]:
ten_z = np.zeros(10)
ten_z[4] = 1
print(ten_z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###  Create a vector with values ranging from 10 to 49.

Level: Easy

In [4]:
ten_fortynine = np.arange(10,50)
print(ten_fortynine)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 3. create two arrays and stack them vertically

Level: Easy

In [20]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,1])
np.vstack((a,b))

array([[1, 2, 3, 4],
       [2, 3, 4, 1]])

### 4. Reverse a vector (first element becomes last).

Level: Easy

In [38]:
a=np.arange(10)
np.flip(a)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 5. Create a 3x3 matrix with values ranging from 0 to 8 

Level: Easy

In [45]:
np.arange(0,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 6. Find indices of non-zero elements from [1,2,0,0,4,0]

Level: Easy

In [50]:
a=np.array([1,2,0,0,4,0])
np.where(a==0)[0]

array([2, 3, 5])

### 7. Create a 10x10 array with random values and find the minimum and maximum values.

Level: Easy

In [99]:
a=np.random.randn(10,10)
print(a.max())
print(a.min())

3.299021061350959
-2.2647828212219876


### 8. Create a random vector of size 30 and find the mean value.

Level: Medium

In [104]:
a=np.random.randn(30)
print(a.mean())

0.36478856261419657


### 9. Create a 2d array with 1 on the border and 0 inside
Level: Medium

In [105]:
oneborder = np.ones((10,10))
oneborder[1:-1, 1:-1] = 0
print(oneborder)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 10. How to add a border (filled with 0's) around an existing array

Level: Medium

In [129]:
azero=np.ones((10,10))
azero=np.pad(azero,1,'constant',constant_values=0)
print(azero)
azero.shape

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


(12, 12)

### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Sample Output:
    
[[ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0.  0.  4.  0.]]
 
 Level: Medium

In [127]:
a=np.zeros((5,5))
a
a[1,0]=1
a[2,1]=2
a[3,2]=3
a[4,3]=4
a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

### 12. Create a 5*5 matrix with random values and normalize it.
Level: Medium

In [155]:
a = np.random.random((5,5))
b= (a - a.min())/(a.max()-a.min())
b

array([[0.68864994, 0.51350011, 0.98285314, 0.25234495, 0.55372401],
       [0.16691142, 0.68767948, 0.83141246, 0.00557384, 0.58747046],
       [0.08136557, 0.69158613, 0.93761901, 0.24216571, 0.98819482],
       [0.64382969, 0.        , 0.03227051, 0.86273959, 0.73953005],
       [0.31284247, 0.31121132, 0.49755168, 0.58970395, 1.        ]])

### 13. How to find common values between two arrays
Level: Medium

In [132]:
a1 = np.arange(10)
a2 = np.arange(1,5)
a3 = np.intersect1d(a1,a2)
a3

array([1, 2, 3, 4])

### 14. Consider a generator function that generates 10 integers and use it to build an array
Level: Medium

In [176]:
def generator():
    a=[]
    for i in range(10):
        a.append(random.randint(10,1000))
    return a

b=np.array(generator())
print(b)
type(b)

[681  37 913 449 150 694 587 971 864 713]


numpy.ndarray

### 15. Subtract the mean of each row of a matrix
Level: Hard

In [184]:
a = np.random.randint(1,50,(10,5))
mean=a.mean(axis=1)
print(mean)
print(a)
b = a.copy()
for i in range(a.shape[0]):
    b[i] = b[i] - mean[i]
print(b)


[30.2 28.  34.  31.2 23.6 23.4 15.2 24.8 20.2 27.8]
[[37 13 17 41 43]
 [48 21 40 17 14]
 [49 40 20 32 29]
 [41 26 37  5 47]
 [15 29 24  2 48]
 [13 13 40  8 43]
 [ 5 41 12  8 10]
 [34 43  5 16 26]
 [ 9  6 49 23 14]
 [16 28 41 15 39]]
[[  6 -17 -13  10  12]
 [ 20  -7  12 -11 -14]
 [ 15   6 -14  -2  -5]
 [  9  -5   5 -26  15]
 [ -8   5   0 -21  24]
 [-10 -10  16 -15  19]
 [-10  25  -3  -7  -5]
 [  9  18 -19  -8   1]
 [-11 -14  28   2  -6]
 [-11   0  13 -12  11]]


### 16. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 
Level: Hard

In [187]:
a =np.random.randint(0,10,(1,3))
b=np.random.randint(0,10,(3,1))
print(a,b)
sums = []
for i in np.nditer(a):
    for j in np.nditer(b):
        sums.append(i+j)
print(sums)
print(np.array(sums).reshape(3,3))

[[9 3 4]] [[3]
 [5]
 [2]]
[12, 14, 11, 6, 8, 5, 7, 9, 6]
[[12 14 11]
 [ 6  8  5]
 [ 7  9  6]]


### 17. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
Level: Hard